### PR TITLE
particleData: update to PDG 2016 values

### PR DESCRIPTION
**Pull request by suhlatwork**
Update the particle data table to the values from the 2016 edition of
the PDG.

### CODE REVIEW

**Comment by bgrube** [comment]
Thanks a lot Sebastian! However, I would propose to keep a copy of the old file (e.g. as "particleDataTable2012.txt"). This way, we have as default the latest and greatest and at the same time it is easy to repeat fits from the publications.

**Comment by suhlatwork** [comment]
Keep the old file around.

**Comment by stefan-wallner** [comment]
I would not update the `particleData/particleDataTable.txt` file, because everyone who updates his ROOTPWA version without carefully checking the commits can obtain (slightly) different results using the updated table without knowing the reason. 
I would create a `particleData/particleDataTable2016.txt` file and perhaps even move `particleData/particleDataTable.txt` to `particleData/particleDataTable2012.txt`. 
If one wants to have the newest one as default, one may adjust `rootpwa.config` accordingly.

**Comment by suhlatwork** [comment]
Add the 2016 data as a new file. Added a card to Trello to take care of making this the default.

**Comment by bgrube** [comment]
Merged. Thank you!

**Pull request merged**
