### PR TITLE
Cherry-pick the recent developments in _v2 for master.

### PR DESCRIPTION
**Pull request by legordian**
Cherry-pick the commits implementing the addition of the NLopt optimizer package and the analytic calculation of the covariance matrix to the master branch. Apart from resolving some conflicts, several commits were modified and one commit was dropped entirely to make the compilation work in the master branch.

### CODE REVIEW

**Comment by legordian** [comment]
Forgot to cherry-pick some stuff, will re-open soon.

**Comment by legordian** [comment]
Forgotten stuff added, pull request reopened.

**Comment by suhlatwork** [comment]
Just to be sure about this: a couple of things from _v2 are still missing in this pull request:
* the improvements to the plotting scripts
* the executables to strip and add back the integral and covariance matrices
* the executable to re-calculate the likelihood from a fit result
* this commit: d8aca8d 'src: Simplify getting intensities.'

**Comment by suhlatwork** [comment]
Compilation of 'pwaLikelihood.cc' requires C++11, so cmake should probably fail if the compiler does not provide this.

**Comment by legordian** [comment]
Implemented your suggestions except for the plotting script improvements, as the plottings scripts should be rewritten in the master in any case. The implementation involved rebasing a number of commits and force-pushing, so a reset is required to properly update your local branches.

**Comment by suhlatwork** [comment]
a1965856a376ce286135e092ab0fc0d572016adf src: Fix bug in complexMatrix.commit 52d933fe081686302f288ee9027547848776e224 src: Cosmetics.
586f72c37506637c5fa30da38b425248c7b1a204 src: Use wave list from fit result.

**Comment by legordian** [comment]
Done! :)

**Pull request merged**
